name: app_paradas
description: "AppParadas: rutas de combi de Lázaro Cárdenas, Michoacán, y buscador de la ruta más rápida."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  maplibre_gl: ">=0.20.0 <1.0.0"
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  web: ^1.1.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
